"""The menu-bar QR code: generated by Core Image, so macOS only. Decoded again with Core Image's
own QR reader, to prove that a phone could read it, not just that an image comes out."""
import sys

import pytest

pytestmark = pytest.mark.skipif(sys.platform != "darwin", reason="Core Image is macOS only")


def decode(rep):
    import objc
    objc.loadBundle("CoreImage", {}, bundle_path="/System/Library/Frameworks/CoreImage.framework")
    CIImage, CIDetector = objc.lookUpClass("CIImage"), objc.lookUpClass("CIDetector")
    image = CIImage.alloc().initWithBitmapImageRep_(rep)
    detector = CIDetector.detectorOfType_context_options_(
        "CIDetectorTypeQRCode", None, {"CIDetectorAccuracy": "CIDetectorAccuracyHigh"})
    return [f.messageString() for f in detector.featuresInImage_(image)]


@pytest.mark.parametrize("url", [
    "http://192.168.1.110:8765",
    "http://10.0.0.7:80",
    "http://192.168.100.200:65535/" + "x" * 80,  # a longer address: a bigger code
])
def test_code_decodes_to_the_url(url):
    from consolelink import menubar_qr
    assert decode(menubar_qr.qr_bitmap(url)) == [url]


def test_bitmap_is_square_crisp_and_big_enough():
    from consolelink import menubar_qr
    rep = menubar_qr.qr_bitmap("http://192.168.1.110:8765", min_pixels=560)
    assert rep.pixelsWide() == rep.pixelsHigh() >= 560
    # every module is a whole number of pixels: the pixel width is a multiple of (modules + 2 * quiet zone)
    modules_with_quiet_zone = 27 + 2 * menubar_qr.QUIET_ZONE  # this URL's code is 27 modules wide
    assert rep.pixelsWide() % modules_with_quiet_zone == 0
    corner = rep.colorAtX_y_(0, 0)
    assert (corner.redComponent(), corner.greenComponent(), corner.blueComponent()) == (1.0, 1.0, 1.0)  # quiet zone


def test_image_is_sized_in_points():
    from consolelink import menubar_qr
    image = menubar_qr.qr_image("http://192.168.1.110:8765", points=280)
    assert (image.size().width, image.size().height) == (280, 280)


def test_warm_up_runs_and_leaves_later_codes_cheap():
    import time
    from consolelink import menubar_qr
    menubar_qr.warm_up()
    start = time.time()
    menubar_qr.qr_bitmap("http://192.168.1.110:8765")
    assert time.time() - start < 0.25  # was ~0.37 s the first time, which froze the USB thread
